<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code_fips');
            $table->string('code_iso');
            $table->string('name');
            $table->timestamps();
        });

        DB::table('countries')->insert([
            ['code_fips' => 'AA', 'code_iso' => 'AW', 'name'=>'Aruba'],
            ['code_fips' => 'AC', 'code_iso' => 'AG', 'name'=>'Antigua and Barbuda'],
            ['code_fips' => 'AE', 'code_iso' => 'AE', 'name'=>'United Arab Emirates'],
            ['code_fips' => 'AF', 'code_iso' => 'AF', 'name'=>'Afghanistan'],
            ['code_fips' => 'AG', 'code_iso' => 'DZ', 'name'=>'Algeria'],
            ['code_fips' => 'AJ', 'code_iso' => 'AZ', 'name'=>'Azerbaijan'],
            ['code_fips' => 'AL', 'code_iso' => 'AL', 'name'=>'Albania'],
            ['code_fips' => 'AM', 'code_iso' => 'AM', 'name'=>'Armenia'],
            ['code_fips' => 'AN', 'code_iso' => 'AD', 'name'=>'Andorra'],
            ['code_fips' => 'AO', 'code_iso' => 'AO', 'name'=>'Angola'],
            ['code_fips' => 'AQ', 'code_iso' => 'AS', 'name'=>'American Samoa'],
            ['code_fips' => 'AR', 'code_iso' => 'AR', 'name'=>'Argentina'],
            ['code_fips' => 'AS', 'code_iso' => 'AU', 'name'=>'Australia'],
            ['code_fips' => 'AT', 'code_iso' => '-', 'name'=>'Ashmore and Cartier Islands'],
            ['code_fips' => 'AU', 'code_iso' => 'AT', 'name'=>'Austria'],
            ['code_fips' => 'AV', 'code_iso' => 'AI', 'name'=>'Anguilla'],
            ['code_fips' => '-', 'code_iso' => 'AX', 'name'=>'Åland Islands'],
            ['code_fips' => 'AY', 'code_iso' => 'AQ', 'name'=>'Antarctica'],
            ['code_fips' => 'BA', 'code_iso' => 'BH', 'name'=>'Bahrain'],
            ['code_fips' => 'BB', 'code_iso' => 'BB', 'name'=>'Barbados'],
            ['code_fips' => 'BC', 'code_iso' => 'BW', 'name'=>'Botswana'],
            ['code_fips' => 'BD', 'code_iso' => 'BM', 'name'=>'Bermuda'],
            ['code_fips' => 'BE', 'code_iso' => 'BE', 'name'=>'Belgium'],
            ['code_fips' => 'BF', 'code_iso' => 'BS', 'name'=>'Bahamas, The'],
            ['code_fips' => 'BG', 'code_iso' => 'BD', 'name'=>'Bangladesh'],
            ['code_fips' => 'BH', 'code_iso' => 'BZ', 'name'=>'Belize'],
            ['code_fips' => 'BK', 'code_iso' => 'BA', 'name'=>'Bosnia and Herzegovina'],
            ['code_fips' => 'BL', 'code_iso' => 'BO', 'name'=>'Bolivia'],
            ['code_fips' => 'TB', 'code_iso' => 'BL', 'name'=>'Saint Barthelemy'],
            ['code_fips' => 'BM', 'code_iso' => 'MM', 'name'=>'Myanmar'],
            ['code_fips' => 'BN', 'code_iso' => 'BJ', 'name'=>'Benin'],
            ['code_fips' => 'BO', 'code_iso' => 'BY', 'name'=>'Belarus'],
            ['code_fips' => 'BP', 'code_iso' => 'SB', 'name'=>'Solomon Islands'],
            ['code_fips' => 'BQ', 'code_iso' => '-', 'name'=>'Navassa Island'],
            ['code_fips' => 'BR', 'code_iso' => 'BR', 'name'=>'Brazil'],
            ['code_fips' => 'BS', 'code_iso' => '-', 'name'=>'Bassas da India'],
            ['code_fips' => 'BT', 'code_iso' => 'BT', 'name'=>'Bhutan'],
            ['code_fips' => 'BU', 'code_iso' => 'BG', 'name'=>'Bulgaria'],
            ['code_fips' => 'BV', 'code_iso' => 'BV', 'name'=>'Bouvet Island'],
            ['code_fips' => 'BX', 'code_iso' => 'BN', 'name'=>'Brunei'],
            ['code_fips' => 'BY', 'code_iso' => 'BI', 'name'=>'Burundi'],
            ['code_fips' => 'CA', 'code_iso' => 'CA', 'name'=>'Canada'],
            ['code_fips' => 'CB', 'code_iso' => 'KH', 'name'=>'Cambodia'],
            ['code_fips' => 'CD', 'code_iso' => 'TD', 'name'=>'Chad'],
            ['code_fips' => 'CE', 'code_iso' => 'LK', 'name'=>'Sri Lanka'],
            ['code_fips' => 'CF', 'code_iso' => 'CG', 'name'=>'Congo, Republic of the'],
            ['code_fips' => 'CG', 'code_iso' => 'CD', 'name'=>'Congo, Democratic Republic of the'],
            ['code_fips' => 'CH', 'code_iso' => 'CN', 'name'=>'China'],
            ['code_fips' => 'CI', 'code_iso' => 'CL', 'name'=>'Chile'],
            ['code_fips' => 'CJ', 'code_iso' => 'KY', 'name'=>'Cayman Islands'],
            ['code_fips' => 'CK', 'code_iso' => 'CC', 'name'=>'Cocos (Keeling) Islands'],
            ['code_fips' => 'CM', 'code_iso' => 'CM', 'name'=>'Cameroon'],
            ['code_fips' => 'CN', 'code_iso' => 'KM', 'name'=>'Comoros'],
            ['code_fips' => 'CO', 'code_iso' => 'CO', 'name'=>'Colombia'],
            ['code_fips' => 'CQ', 'code_iso' => 'MP', 'name'=>'Northern Mariana Islands'],
            ['code_fips' => 'CR', 'code_iso' => '-', 'name'=>'Coral Sea Islands'],
            ['code_fips' => 'CS', 'code_iso' => 'CR', 'name'=>'Costa Rica'],
            ['code_fips' => 'CT', 'code_iso' => 'CF', 'name'=>'Central African Republic'],
            ['code_fips' => 'CU', 'code_iso' => 'CU', 'name'=>'Cuba'],
            ['code_fips' => 'CV', 'code_iso' => 'CV', 'name'=>'Cape Verde'],
            ['code_fips' => 'CW', 'code_iso' => 'CK', 'name'=>'Cook Islands'],
            ['code_fips' => 'CY', 'code_iso' => 'CY', 'name'=>'Cyprus'],
            ['code_fips' => 'DA', 'code_iso' => 'DK', 'name'=>'Denmark'],
            ['code_fips' => 'DJ', 'code_iso' => 'DJ', 'name'=>'Djibouti'],
            ['code_fips' => 'DO', 'code_iso' => 'DM', 'name'=>'Dominica'],
            ['code_fips' => 'DR', 'code_iso' => 'DO', 'name'=>'Dominican Republic'],
            ['code_fips' => 'EC', 'code_iso' => 'EC', 'name'=>'Ecuador'],
            ['code_fips' => 'EG', 'code_iso' => 'EG', 'name'=>'Egypt'],
            ['code_fips' => 'EI', 'code_iso' => 'IE', 'name'=>'Ireland'],
            ['code_fips' => 'EK', 'code_iso' => 'GQ', 'name'=>'Equatorial Guinea'],
            ['code_fips' => 'EN', 'code_iso' => 'EE', 'name'=>'Estonia'],
            ['code_fips' => 'ER', 'code_iso' => 'ER', 'name'=>'Eritrea'],
            ['code_fips' => 'ES', 'code_iso' => 'SV', 'name'=>'El Salvador'],
            ['code_fips' => 'ET', 'code_iso' => 'ET', 'name'=>'Ethiopia'],
            ['code_fips' => 'EZ', 'code_iso' => 'CZ', 'name'=>'Czech Republic'],
            ['code_fips' => 'FG', 'code_iso' => 'GF', 'name'=>'French Guiana'],
            ['code_fips' => 'FI', 'code_iso' => 'FI', 'name'=>'Finland'],
            ['code_fips' => 'FJ', 'code_iso' => 'FJ', 'name'=>'Fiji'],
            ['code_fips' => 'FK', 'code_iso' => 'FK', 'name'=>'Falkland Islands (Islas Malvinas)'],
            ['code_fips' => 'FM', 'code_iso' => 'FM', 'name'=>'Micronesia, Federated States of'],
            ['code_fips' => 'FO', 'code_iso' => 'FO', 'name'=>'Faroe Islands'],
            ['code_fips' => 'FP', 'code_iso' => 'PF', 'name'=>'French Polynesia'],
            ['code_fips' => 'FR', 'code_iso' => 'FR', 'name'=>'France'],
            ['code_fips' => 'FS', 'code_iso' => 'TF', 'name'=>'French Southern and Antarctic Lands'],
            ['code_fips' => 'GA', 'code_iso' => 'GM', 'name'=>'Gambia, The'],
            ['code_fips' => 'GB', 'code_iso' => 'GA', 'name'=>'Gabon'],
            ['code_fips' => 'GG', 'code_iso' => 'GE', 'name'=>'Georgia'],
            ['code_fips' => 'GH', 'code_iso' => 'GH', 'name'=>'Ghana'],
            ['code_fips' => 'GI', 'code_iso' => 'GI', 'name'=>'Gibraltar'],
            ['code_fips' => 'GJ', 'code_iso' => 'GD', 'name'=>'Grenada'],
            ['code_fips' => 'GK', 'code_iso' => 'GG', 'name'=>'Guernsey'],
            ['code_fips' => 'GL', 'code_iso' => 'GL', 'name'=>'Greenland'],
            ['code_fips' => 'GM', 'code_iso' => 'DE', 'name'=>'Germany'],
            ['code_fips' => 'GP', 'code_iso' => 'GP', 'name'=>'Guadeloupe'],
            ['code_fips' => 'GQ', 'code_iso' => 'GU', 'name'=>'Guam'],
            ['code_fips' => 'GR', 'code_iso' => 'GR', 'name'=>'Greece'],
            ['code_fips' => 'GT', 'code_iso' => 'GT', 'name'=>'Guatemala'],
            ['code_fips' => 'GV', 'code_iso' => 'GN', 'name'=>'Guinea'],
            ['code_fips' => 'GY', 'code_iso' => 'GY', 'name'=>'Guyana'],
            ['code_fips' => 'HA', 'code_iso' => 'HT', 'name'=>'Haiti'],
            ['code_fips' => 'HK', 'code_iso' => 'HK', 'name'=>'Hong Kong'],
            ['code_fips' => 'HM', 'code_iso' => 'HM', 'name'=>'Heard Island and McDonald Islands'],
            ['code_fips' => 'HO', 'code_iso' => 'HN', 'name'=>'Honduras'],
            ['code_fips' => 'HR', 'code_iso' => 'HR', 'name'=>'Croatia'],
            ['code_fips' => 'HU', 'code_iso' => 'HU', 'name'=>'Hungary'],
            ['code_fips' => 'IC', 'code_iso' => 'IS', 'name'=>'Iceland'],
            ['code_fips' => 'ID', 'code_iso' => 'ID', 'name'=>'Indonesia'],
            ['code_fips' => 'IM', 'code_iso' => 'IM', 'name'=>'Isle of Man'],
            ['code_fips' => 'IN', 'code_iso' => 'IN', 'name'=>'India'],
            ['code_fips' => 'IO', 'code_iso' => 'IO', 'name'=>'British Indian Ocean Territory'],
            ['code_fips' => 'IP', 'code_iso' => '-', 'name'=>'Clipperton Island'],
            ['code_fips' => 'IR', 'code_iso' => 'IR', 'name'=>'Iran'],
            ['code_fips' => 'IS', 'code_iso' => 'IL', 'name'=>'Israel'],
            ['code_fips' => 'IT', 'code_iso' => 'IT', 'name'=>'Italy'],
            ['code_fips' => 'IV', 'code_iso' => 'CI', 'name'=>"Cote d'Ivoire"],
            ['code_fips' => 'IZ', 'code_iso' => 'IQ', 'name'=>'Iraq'],
            ['code_fips' => 'JA', 'code_iso' => 'JP', 'name'=>'Japan'],
            ['code_fips' => 'JE', 'code_iso' => 'JE', 'name'=>'Jersey'],
            ['code_fips' => 'JM', 'code_iso' => 'JM', 'name'=>'Jamaica'],
            ['code_fips' => 'JN', 'code_iso' => 'SJ', 'name'=>'Jan Mayen'],
            ['code_fips' => 'JO', 'code_iso' => 'JO', 'name'=>'Jordan'],
            ['code_fips' => 'JU', 'code_iso' => '-', 'name'=>'Juan de Nova Island'],
            ['code_fips' => 'KE', 'code_iso' => 'KE', 'name'=>'Kenya'],
            ['code_fips' => 'KG', 'code_iso' => 'KG', 'name'=>'Kyrgyzstan'],
            ['code_fips' => 'KN', 'code_iso' => 'KP', 'name'=>'Korea, North'],
            ['code_fips' => 'KR', 'code_iso' => 'KI', 'name'=>'Kiribati'],
            ['code_fips' => 'KS', 'code_iso' => 'KR', 'name'=>'Korea, South'],
            ['code_fips' => 'KT', 'code_iso' => 'CX', 'name'=>'Christmas Island'],
            ['code_fips' => 'KU', 'code_iso' => 'KW', 'name'=>'Kuwait'],
            ['code_fips' => 'KV', 'code_iso' => 'XK', 'name'=>'Kosovo'],
            ['code_fips' => 'KZ', 'code_iso' => 'KZ', 'name'=>'Kazakhstan'],
            ['code_fips' => 'LA', 'code_iso' => 'LA', 'name'=>'Laos'],
            ['code_fips' => 'LE', 'code_iso' => 'LB', 'name'=>'Lebanon'],
            ['code_fips' => 'LG', 'code_iso' => 'LV', 'name'=>'Latvia'],
            ['code_fips' => 'LH', 'code_iso' => 'LT', 'name'=>'Lithuania'],
            ['code_fips' => 'LI', 'code_iso' => 'LR', 'name'=>'Liberia'],
            ['code_fips' => 'LO', 'code_iso' => 'SK', 'name'=>'Slovakia'],
            ['code_fips' => '-', 'code_iso' => 'UM', 'name'=>'United States Minor Outlying Islands'],
            ['code_fips' => 'LS', 'code_iso' => 'LI', 'name'=>'Liechtenstein'],
            ['code_fips' => 'LT', 'code_iso' => 'LS', 'name'=>'Lesotho'],
            ['code_fips' => 'LU', 'code_iso' => 'LU', 'name'=>'Luxembourg'],
            ['code_fips' => 'LY', 'code_iso' => 'LY', 'name'=>'Libya'],
            ['code_fips' => 'MA', 'code_iso' => 'MG', 'name'=>'Madagascar'],
            ['code_fips' => 'MB', 'code_iso' => 'MQ', 'name'=>'Martinique'],
            ['code_fips' => 'MC', 'code_iso' => 'MO', 'name'=>'Macau'],
            ['code_fips' => 'MD', 'code_iso' => 'MD', 'name'=>'Moldova, Republic of'],
            ['code_fips' => 'MF', 'code_iso' => 'YT', 'name'=>'Mayotte'],
            ['code_fips' => 'MG', 'code_iso' => 'MN', 'name'=>'Mongolia'],
            ['code_fips' => 'MH', 'code_iso' => 'MS', 'name'=>'Montserrat'],
            ['code_fips' => 'MI', 'code_iso' => 'MW', 'name'=>'Malawi'],
            ['code_fips' => 'MJ', 'code_iso' => 'ME', 'name'=>'Montenegro'],
            ['code_fips' => 'MK', 'code_iso' => 'MK', 'name'=>'The Former Yugoslav Republic of Macedonia'],
            ['code_fips' => 'ML', 'code_iso' => 'ML', 'name'=>'Mali'],
            ['code_fips' => 'MN', 'code_iso' => 'MC', 'name'=>'Monaco'],
            ['code_fips' => 'MO', 'code_iso' => 'MA', 'name'=>'Morocco'],
            ['code_fips' => 'MP', 'code_iso' => 'MU', 'name'=>'Mauritius'],
            ['code_fips' => 'MR', 'code_iso' => 'MR', 'name'=>'Mauritania'],
            ['code_fips' => 'MT', 'code_iso' => 'MT', 'name'=>'Malta'],
            ['code_fips' => 'MU', 'code_iso' => 'OM', 'name'=>'Oman'],
            ['code_fips' => 'MV', 'code_iso' => 'MV', 'name'=>'Maldives'],
            ['code_fips' => 'MX', 'code_iso' => 'MX', 'name'=>'Mexico'],
            ['code_fips' => 'MY', 'code_iso' => 'MY', 'name'=>'Malaysia'],
            ['code_fips' => 'MZ', 'code_iso' => 'MZ', 'name'=>'Mozambique'],
            ['code_fips' => 'NC', 'code_iso' => 'NC', 'name'=>'New Caledonia'],
            ['code_fips' => 'NE', 'code_iso' => 'NU', 'name'=>'Niue'],
            ['code_fips' => 'NF', 'code_iso' => 'NF', 'name'=>'Norfolk Island'],
            ['code_fips' => 'NG', 'code_iso' => 'NE', 'name'=>'Niger'],
            ['code_fips' => 'NH', 'code_iso' => 'VU', 'name'=>'Vanuatu'],
            ['code_fips' => 'NI', 'code_iso' => 'NG', 'name'=>'Nigeria'],
            ['code_fips' => 'NL', 'code_iso' => 'NL', 'name'=>'Netherlands'],
            ['code_fips' => 'NM', 'code_iso' => '', 'name'=>"No Man's Land"],
            ['code_fips' => 'NO', 'code_iso' => 'NO', 'name'=>'Norway'],
            ['code_fips' => 'NP', 'code_iso' => 'NP', 'name'=>'Nepal'],
            ['code_fips' => 'NR', 'code_iso' => 'NR', 'name'=>'Nauru'],
            ['code_fips' => 'NS', 'code_iso' => 'SR', 'name'=>'Suriname'],
            ['code_fips' => '-', 'code_iso' => 'BQ', 'name'=>'Bonaire, Sint Eustatius and Saba'],
            ['code_fips' => 'NU', 'code_iso' => 'NI', 'name'=>'Nicaragua'],
            ['code_fips' => 'NZ', 'code_iso' => 'NZ', 'name'=>'New Zealand'],
            ['code_fips' => 'PA', 'code_iso' => 'PY', 'name'=>'Paraguay'],
            ['code_fips' => 'PC', 'code_iso' => 'PN', 'name'=>'Pitcairn Islands'],
            ['code_fips' => 'PE', 'code_iso' => 'PE', 'name'=>'Peru'],
            ['code_fips' => 'PF', 'code_iso' => '-', 'name'=>'Paracel Islands'],
            ['code_fips' => 'PG', 'code_iso' => '-', 'name'=>'Spratly Islands'],
            ['code_fips' => 'PK', 'code_iso' => 'PK', 'name'=>'Pakistan'],
            ['code_fips' => 'PL', 'code_iso' => 'PL', 'name'=>'Poland'],
            ['code_fips' => 'PM', 'code_iso' => 'PA', 'name'=>'Panama'],
            ['code_fips' => 'PO', 'code_iso' => 'PT', 'name'=>'Portugal'],
            ['code_fips' => 'PP', 'code_iso' => 'PG', 'name'=>'Papua New Guinea'],
            ['code_fips' => 'PS', 'code_iso' => 'PW', 'name'=>'Palau'],
            ['code_fips' => 'PU', 'code_iso' => 'GW', 'name'=>'Guinea-Bissau'],
            ['code_fips' => 'QA', 'code_iso' => 'QA', 'name'=>'Qatar'],
            ['code_fips' => 'RE', 'code_iso' => 'RE', 'name'=>'Reunion'],
            ['code_fips' => 'RI', 'code_iso' => 'RS', 'name'=>'Serbia'],
            ['code_fips' => 'RM', 'code_iso' => 'MH', 'name'=>'Marshall Islands'],
            ['code_fips' => 'RN', 'code_iso' => 'MF', 'name'=>'Saint Martin'],
            ['code_fips' => 'RO', 'code_iso' => 'RO', 'name'=>'Romania'],
            ['code_fips' => 'RP', 'code_iso' => 'PH', 'name'=>'Philippines'],
            ['code_fips' => 'RQ', 'code_iso' => 'PR', 'name'=>'Puerto Rico'],
            ['code_fips' => 'RS', 'code_iso' => 'RU', 'name'=>'Russia'],
            ['code_fips' => 'RW', 'code_iso' => 'RW', 'name'=>'Rwanda'],
            ['code_fips' => 'SA', 'code_iso' => 'SA', 'name'=>'Saudi Arabia'],
            ['code_fips' => 'SB', 'code_iso' => 'PM', 'name'=>'Saint Pierre and Miquelon'],
            ['code_fips' => 'SC', 'code_iso' => 'KN', 'name'=>'Saint Kitts and Nevis'],
            ['code_fips' => 'SE', 'code_iso' => 'SC', 'name'=>'Seychelles'],
            ['code_fips' => 'SF', 'code_iso' => 'ZA', 'name'=>'South Africa'],
            ['code_fips' => 'SG', 'code_iso' => 'SN', 'name'=>'Senegal'],
            ['code_fips' => 'SH', 'code_iso' => 'SH', 'name'=>'Saint Helena'],
            ['code_fips' => 'SI', 'code_iso' => 'SI', 'name'=>'Slovenia'],
            ['code_fips' => 'SL', 'code_iso' => 'SL', 'name'=>'Sierra Leone'],
            ['code_fips' => 'SM', 'code_iso' => 'SM', 'name'=>'San Marino'],
            ['code_fips' => 'SN', 'code_iso' => 'SG', 'name'=>'Singapore'],
            ['code_fips' => 'SO', 'code_iso' => 'SO', 'name'=>'Somalia'],
            ['code_fips' => 'SP', 'code_iso' => 'ES', 'name'=>'Spain'],
            ['code_fips' => '-', 'code_iso' => 'SS', 'name'=>'South Sudan'],
            ['code_fips' => 'ST', 'code_iso' => 'LC', 'name'=>'Saint Lucia'],
            ['code_fips' => 'SU', 'code_iso' => 'SD', 'name'=>'Sudan'],
            ['code_fips' => 'SV', 'code_iso' => 'SJ', 'name'=>'Svalbard'],
            ['code_fips' => 'SW', 'code_iso' => 'SE', 'name'=>'Sweden'],
            ['code_fips' => 'SX', 'code_iso' => 'GS', 'name'=>'South Georgia and the Islands'],
            ['code_fips' => 'NN', 'code_iso' => 'SX', 'name'=>'Sint Maarten'],
            ['code_fips' => 'SY', 'code_iso' => 'SY', 'name'=>'Syrian Arab Republic'],
            ['code_fips' => 'SZ', 'code_iso' => 'CH', 'name'=>'Switzerland'],
            ['code_fips' => 'TD', 'code_iso' => 'TT', 'name'=>'Trinidad and Tobago'],
            ['code_fips' => 'TE', 'code_iso' => '-', 'name'=>'Tromelin Island'],
            ['code_fips' => 'TH', 'code_iso' => 'TH', 'name'=>'Thailand'],
            ['code_fips' => 'TI', 'code_iso' => 'TJ', 'name'=>'Tajikistan'],
            ['code_fips' => 'TK', 'code_iso' => 'TC', 'name'=>'Turks and Caicos Islands'],
            ['code_fips' => 'TL', 'code_iso' => 'TK', 'name'=>'Tokelau'],
            ['code_fips' => 'TN', 'code_iso' => 'TO', 'name'=>'Tonga'],
            ['code_fips' => 'TO', 'code_iso' => 'TG', 'name'=>'Togo'],
            ['code_fips' => 'TP', 'code_iso' => 'ST', 'name'=>'Sao Tome and Principe'],
            ['code_fips' => 'TS', 'code_iso' => 'TN', 'name'=>'Tunisia'],
            ['code_fips' => 'TT', 'code_iso' => 'TL', 'name'=>'East Timor'],
            ['code_fips' => 'TU', 'code_iso' => 'TR', 'name'=>'Turkey'],
            ['code_fips' => 'TV', 'code_iso' => 'TV', 'name'=>'Tuvalu'],
            ['code_fips' => 'TW', 'code_iso' => 'TW', 'name'=>'Taiwan'],
            ['code_fips' => 'TX', 'code_iso' => 'TM', 'name'=>'Turkmenistan'],
            ['code_fips' => 'TZ', 'code_iso' => 'TZ', 'name'=>'Tanzania, United Republic of'],
            ['code_fips' => 'UC', 'code_iso' => 'CW', 'name'=>'Curacao'],
            ['code_fips' => 'UG', 'code_iso' => 'UG', 'name'=>'Uganda'],
            ['code_fips' => 'UK', 'code_iso' => 'GB', 'name'=>'United Kingdom'],
            ['code_fips' => 'UP', 'code_iso' => 'UA', 'name'=>'Ukraine'],
            ['code_fips' => 'US', 'code_iso' => 'US', 'name'=>'United States'],
            ['code_fips' => 'UV', 'code_iso' => 'BF', 'name'=>'Burkina Faso'],
            ['code_fips' => 'UY', 'code_iso' => 'UY', 'name'=>'Uruguay'],
            ['code_fips' => 'UZ', 'code_iso' => 'UZ', 'name'=>'Uzbekistan'],
            ['code_fips' => 'VC', 'code_iso' => 'VC', 'name'=>'Saint Vincent and the Grenadines'],
            ['code_fips' => 'VE', 'code_iso' => 'VE', 'name'=>'Venezuela'],
            ['code_fips' => 'VI', 'code_iso' => 'VG', 'name'=>'British Virgin Islands'],
            ['code_fips' => 'VM', 'code_iso' => 'VN', 'name'=>'Vietnam'],
            ['code_fips' => 'VQ', 'code_iso' => 'VI', 'name'=>'Virgin Islands (US)'],
            ['code_fips' => 'VT', 'code_iso' => 'VA', 'name'=>'Holy See (Vatican City)'],
            ['code_fips' => 'WA', 'code_iso' => 'NA', 'name'=>'Namibia'],
            ['code_fips' => 'WE', 'code_iso' => 'PS', 'name'=>'Palestine, State of'],
            ['code_fips' => 'WF', 'code_iso' => 'WF', 'name'=>'Wallis and Futuna'],
            ['code_fips' => 'WI', 'code_iso' => 'EH', 'name'=>'Western Sahara'],
            ['code_fips' => 'WS', 'code_iso' => 'WS', 'name'=>'Samoa'],
            ['code_fips' => 'WZ', 'code_iso' => 'SZ', 'name'=>'Swaziland'],
            ['code_fips' => 'YI', 'code_iso' => 'CS', 'name'=>'Serbia and Montenegro'],
            ['code_fips' => 'YM', 'code_iso' => 'YE', 'name'=>'Yemen'],
            ['code_fips' => 'ZA', 'code_iso' => 'ZM', 'name'=>'Zambia'],
            ['code_fips' => 'ZI', 'code_iso' => 'ZW', 'name'=>'Zimbabwe']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
